import { beforeEach, describe, expect, it, vi } from "vitest";
import { GetYouTubeTranscript, GetYouTubeTranscriptError, verifyWebhookSignature } from "../src/index.js";

const BASE = "https://getyoutubetranscript.com/api/v1";
const BATCH_ID = "324eb615-e4d5-4b3c-b8e7-04235671066b";

function jsonResponse(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
}

function batch(status: string, extra: Record<string, unknown> = {}) {
  return { success: true, data: { batch_id: BATCH_ID, status, total: 3, pending: 0, ...extra } };
}

describe("batch methods", () => {
  let fetchMock: ReturnType<typeof vi.fn>;
  let client: GetYouTubeTranscript;

  beforeEach(() => {
    fetchMock = vi.fn();
    client = new GetYouTubeTranscript({ apiKey: "sk_live_test123", fetch: fetchMock as unknown as typeof fetch });
  });

  it("getTranscriptLanguages sends the video param", async () => {
    const data = { video_id: "kJQP7kiw5Fk", default_language_code: "en", languages: [{ language_code: "en", name: "English", caption_type: "manual" }] };
    fetchMock.mockResolvedValueOnce(jsonResponse(200, { success: true, data }));
    expect(await client.getTranscriptLanguages({ v: "https://youtu.be/kJQP7kiw5Fk" })).toEqual(data);
    expect(fetchMock.mock.calls[0][0]).toBe(`${BASE}/transcript/languages?v=https%3A%2F%2Fyoutu.be%2FkJQP7kiw5Fk`);
  });

  it("createBatch POSTs a JSON body with the Idempotency-Key header", async () => {
    fetchMock.mockResolvedValueOnce(jsonResponse(202, batch("queued", { webhook_secret: "whsec_x" })));
    const result = await client.createBatch({
      videos: ["jNQXAC9IVRw", "https://youtu.be/dQw4w9WgXcQ"],
      language: "es",
      timestamps: true,
      webhookUrl: "https://example.com/hook",
      idempotencyKey: "job-42",
    });

    expect(result.batch_id).toBe(BATCH_ID);
    const [url, init] = fetchMock.mock.calls[0];
    expect(url).toBe(`${BASE}/batch`);
    expect(init.method).toBe("POST");
    expect(init.headers).toMatchObject({ Authorization: "Bearer sk_live_test123", "Idempotency-Key": "job-42" });
    expect(JSON.parse(init.body)).toEqual({
      videos: ["jNQXAC9IVRw", "https://youtu.be/dQw4w9WgXcQ"],
      language: "es",
      timestamps: true,
      webhook_url: "https://example.com/hook",
    });
  });

  it("createBatch omits unset options", async () => {
    fetchMock.mockResolvedValueOnce(jsonResponse(202, batch("queued")));
    await client.createBatch({ videos: ["jNQXAC9IVRw"] });
    const [, init] = fetchMock.mock.calls[0];
    expect(JSON.parse(init.body)).toEqual({ videos: ["jNQXAC9IVRw"] });
    expect(init.headers).not.toHaveProperty("Idempotency-Key");
  });

  it("createBatch rejects an empty list without calling the API", async () => {
    await expect(client.createBatch({ videos: [] })).rejects.toThrow(/at least one video/);
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it("createBatch surfaces the API error code", async () => {
    fetchMock.mockResolvedValueOnce(
      jsonResponse(429, { success: false, code: "TOO_MANY_BATCHES", message: "You can have at most 5 unfinished batches." }),
    );
    const error = await client.createBatch({ videos: ["jNQXAC9IVRw"] }).catch((e: unknown) => e);
    expect(error).toBeInstanceOf(GetYouTubeTranscriptError);
    expect((error as GetYouTubeTranscriptError).code).toBe("TOO_MANY_BATCHES");
    expect((error as GetYouTubeTranscriptError).statusCode).toBe(429);
  });

  it("getBatch sends id, offset and limit", async () => {
    fetchMock.mockResolvedValueOnce(jsonResponse(200, batch("completed", { items: [], next_offset: null })));
    await client.getBatch({ id: BATCH_ID, offset: 20, limit: 10 });
    expect(fetchMock.mock.calls[0][0]).toBe(`${BASE}/batch?id=${BATCH_ID}&offset=20&limit=10`);
  });

  it("waitForBatch polls until completed, then collects every page", async () => {
    fetchMock
      .mockResolvedValueOnce(jsonResponse(200, batch("processing", { pending: 2, items: [] })))
      .mockResolvedValueOnce(jsonResponse(200, batch("completed", { items: [{ position: 0 }] })))
      .mockResolvedValueOnce(jsonResponse(200, batch("completed", { items: [{ position: 0 }, { position: 1 }], next_offset: 2 })))
      .mockResolvedValueOnce(jsonResponse(200, batch("completed", { items: [{ position: 2 }], next_offset: null })));

    const result = await client.waitForBatch(BATCH_ID, { pollIntervalMs: 0, pageSize: 2 });

    expect(result.items?.map((item) => item.position)).toEqual([0, 1, 2]);
    expect(result.next_offset).toBeNull();
    expect(fetchMock).toHaveBeenCalledTimes(4);
  });

  it("waitForBatch times out", async () => {
    fetchMock.mockResolvedValue(jsonResponse(200, batch("processing", { pending: 3, items: [] })));
    await expect(client.waitForBatch(BATCH_ID, { pollIntervalMs: 0, timeoutMs: 0 })).rejects.toThrow(/not completed/);
  });
});

// Generated by the API's own signer (app/lib/batch/webhookDelivery.ts signWebhookBody),
// so this proves the SDK and the API agree byte for byte.
const SERVER_BODY =
  '{"event":"batch.completed","batch_id":"324eb615-e4d5-4b3c-b8e7-04235671066b","status":"completed","total":3,"succeeded":2,"failed":1,"credits_charged":2}';
const SERVER_HEADER = "t=1790000000,v1=ec02d3c715a86cce454f4403eadc3b44077ed4289b699f4333455dc789fa9a4f";
const SECRET = "whsec_test_secret";

describe("verifyWebhookSignature", () => {
  it("accepts a signature produced by the API", async () => {
    expect(await verifyWebhookSignature(SERVER_BODY, SERVER_HEADER, SECRET, { now: 1790000000 })).toBe(true);
    expect(await verifyWebhookSignature(new TextEncoder().encode(SERVER_BODY), SERVER_HEADER, SECRET, { now: 1790000100 })).toBe(true);
  });

  it.each([
    ["changed body", SERVER_BODY + " ", SERVER_HEADER, SECRET, 1790000000],
    ["wrong secret", SERVER_BODY, SERVER_HEADER, "whsec_other", 1790000000],
    ["too old", SERVER_BODY, SERVER_HEADER, SECRET, 1790000000 + 301],
    ["swapped timestamp", SERVER_BODY, SERVER_HEADER.replace("t=1790000000", "t=1790000001"), SECRET, 1790000000],
    ["missing header", SERVER_BODY, null, SECRET, 1790000000],
    ["garbage header", SERVER_BODY, "garbage", SECRET, 1790000000],
    ["empty secret", SERVER_BODY, SERVER_HEADER, "", 1790000000],
  ])("rejects %s", async (_label, body, header, secret, now) => {
    expect(await verifyWebhookSignature(body, header, secret, { now })).toBe(false);
  });

  it("can skip the age check", async () => {
    expect(await verifyWebhookSignature(SERVER_BODY, SERVER_HEADER, SECRET, { toleranceSeconds: 0, now: 0 })).toBe(true);
  });
});
